name: MinecraftSurvivalEvolved
version: 0.2
author: EndermansEnd
main: de.julianSauer.minecraftSurvivalEvolved.main.ThisPlugin
load: STARTUP
commands:
  mse:
    description: Access to all Minecraft Survival Evolved commands
    usage: /mse [command]
permissions:
  MinecraftSurvivalEvolved.*:
    Children:
      MinecraftSurvivalEvolved.ForceTame: op
  MinecraftSurvivalEvolved.ForceTame:
    description: Allows to force tame entities
